### ISSUE TITLE
NodeJS added to netCDF documentation.

### ISSUE THREAD

**Issue by WardF** [swillner/netcdf4-js#1]
Not an issue, per se.  Based on the email you sent, we've added netcdf4-js to our list of software and have highlighted it in the release notes for the upcoming `4.4.0` release.  You can view this at https://github.com/Unidata/netcdf-c/blob/master/RELEASE_NOTES.md for the time being, and it will go live on the Unidata netcdf-c website (http://www.unidata.ucar.edu/software/netcdf/docs) when the upcoming release goes live.

Thanks for telling us about this, it looks great and we're very excited to have an interface for NodeJS :).

**Comment by swillner** [comment]
Thank you!
