### ISSUE TITLE
unable to install it

### ISSUE THREAD

**Issue by ehsan99999** [swillner/netcdf4-js#14]
I have been strugelling to install this moudle for more that two days and I couldn't. Could you please let me know which step I'm missing?

Here is the error I get on nodejs:

D:\master\nodeTut>npm install netcdf4
> netcdf4@0.3.1 install D:\master\nodeTut\node_modules\netcdf4
> node-gyp rebuild

D:\master\nodeTut\node_modules\netcdf4>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:483:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:508:16)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)
gyp ERR! System Windows_NT 10.0.16299
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\master\nodeTut\node_modules\netcdf4
gyp ERR! node -v v8.11.2
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN enoent ENOENT: no such file or directory, open 'D:\master\nodeTut\package.json'
npm WARN nodeTut No description
npm WARN nodeTut No repository field.
npm WARN nodeTut No README data
npm WARN nodeTut No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! netcdf4@0.3.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the netcdf4@0.3.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Ehsan\AppData\Roaming\npm-cache\_logs\2018-06-11T22_02_31_364Z-debug.log

**Comment by fridgerator** [comment]
First off, there is no windows support yet.  I have a branch with windows working, but there are hardcoded netcdf paths, see [here](https://github.com/swillner/netcdf4-js/compare/master...fridgerator:master)

Besides that, It looks like you have 2 issues:

* Python is not found or installed, node-gyp requires python 2.7  Do you have it installed?
* There is no package.json file in the directory you're trying to install it in.  Ensure there is a package.json file (run `npm init` if there is not)

**Comment by swillner** [comment]
yes, you will need to install all prerequisites of node-gyp first: https://github.com/nodejs/node-gyp#on-windows
