### ISSUE TITLE
Node 10 support?

### ISSUE THREAD

**Issue by theophilusx** [swillner/netcdf4-js#16]
I recently tried installing this package with Node 10 and it failed with errors about gyp incompatibility. Before I dig into this further, I wanted to know if there are plans to make it compatible with node 10+? It is many many years since I did any C/C++ and I've not built any node modules which interface with C++, but happy to try and have a go, but thought I'd check to see if this has already been started or if it is a known issue with an easy fix etc. 

thanks,

Tim

**Comment by theophilusx** [comment]
@ianbelcher  No, not yet. If nothing has moved by the time we finish our current dev milestones and we start looking at upgrading to node 10, I probably will. However, last time I did C/C++ was around 1996!

**Comment by adam-nielsen** [comment]
I've made an attempt at updating the code for Node 10 in PR #17.  It seems to work for me but I haven't used netcdf4-js before so I don't really have any way of telling whether it works properly other than it compiles.

**Comment by theophilusx** [comment]
@adam-nielsen I'll try to find space to try out your update and see if it works under node 10. Might be a couple of weeks away thought as I have to finish off some stuff first.

**Comment by swillner** [comment]
now fixed in version `0.4.0` ;)

**Comment by adam-nielsen** [comment]
You're welcome!  Glad it was useful.
