### ISSUE TITLE
Cannot utilize in Windows 10

### ISSUE THREAD

**Issue by spencermize** [swillner/netcdf4-js#20]
- My NETCDF_DIR variable is set
- It seems to compile properly (though it does warn a few variants of this during compilation): 
```
xxx\node_modules\netcdf4\src\variable.cpp(961): warning C4996: 'v8::Value::NumberValue': was declared deprecatedc:\users\xxx\.node-gyp\10.15.0\include\node\v8.h(2478): note: see declaration of 'v8::Value::Int32Value' [xxx\node_modules\netcdf4\build\netcdf4.vcxproj])
```
- When I run the require statement, I get:
```
The specified module could not be found. \\?\xxx\node_modules\netcdf4\build\Release\netcdf4.node Error: The specified module could not be found.
\\?\xxx\node_modules\netcdf4\build\Release\netcdf4.node
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:718:18)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at xxx\routes\api.js:6:19
```
- The netcdf4.node file is present in the directory, and if I copy it and load it from another folder I get the same error.
- I'm using Webpack 4, Node 10, Windows 10 Pro, and have used node-gyp successfully on other projects on this machine.

Any help you can provide would be hugely appreciated!

**Comment by spencermize** [comment]
Update: my same exact configuration works in Ubuntu, so my code doesn't seem to be at fault. I think that also rules out Webpack?

**Comment by swillner** [comment]
Hey, it looks like this might be due to a library dependency not being found (https://stackoverflow.com/a/41272553), which is probably the NetCDF DLL in this case. Can you make sure Windows finds it?

**Comment by spencermize** [comment]
Thanks for the quick response! Also: good catch. https://www.unidata.ucar.edu/software/netcdf/netcdf-4/newdocs/netcdf-install/Installing-the-DLL.html#Installing-the-DLL contains a list of DLLs in the NetCDF suite - the installer apparently failed to add the directory to my PATH variable. 

https://github.com/lucasg/Dependencies helped verify that was the issue. In my case, simply updating the PATH to contain the netCDF/bin directory solved my issue.

All is good now. Thanks!
