### ISSUE TITLE
Get variable attributes

### ISSUE THREAD

**Issue by zevanb** [swillner/netcdf4-js#6]
Hello,

First, thank you for your package, it's very useful ! 
I have an issue with variables attributes. it seems there are parameters (offset, scale_factor) that need to be applied on the data to get the expected value. 
I thought it was stored on attributes (file.root.variables.[attributeName].attributes ) but I keep getting an "Operation not permitted".

Are they stored somewhere else or am I doing something wrong ?

Thank you

**Comment by swillner** [comment]
Hi, sorry, there was a bug reading attributes of variables. It's now fixed, including some tests. Your approach should be working now ;)

**Comment by zevanb** [comment]
Works fine. thank you !
