### ISSUE TITLE
Air-quality slice level variable and re-write the file

### ISSUE THREAD

**Issue by JonathanVandal** [swillner/netcdf4-js#7]
Hi,

It's possible to re-write a netcdf file with your library ? I have a variable named level (0, 50, 250, 500, 1000, 2000, 3000, 5000 m) and I'd like to get the level 0 and re-write the .nc file with just the level 0.

I want to know if your library can write .nc file or we can just read .nc files.

**Comment by swillner** [comment]
Hi @JonathanVandal,

Yes, it is possible to write NetCDF library with netcdf4-js. It is, however, easiest to write your altered level-0-only data to a new file while reading from the original file. Just have a look at the methods' descriptions in README.md.
