### ISSUE TITLE
Windows Support?

### ISSUE THREAD

**Issue by luastoned** [swillner/netcdf4-js#9]
Hi, are there any plans for supporting Windows?
Node is compiled with VS, thus requires modules to be built with that as well.
The problem is that VS does not compile C99, ie. variable size arrays like here:

    Attribute.cpp(57): error C2131: expression did not evaluate to a constant

**Comment by swillner** [comment]
hmm, will look into that... but windows support would be good

**Comment by fridgerator** [comment]
I am building desktop software and also need windows support!! 💯 👍

**Comment by fridgerator** [comment]
@luastoned @swillner 

I was able to get windows working here : https://github.com/swillner/netcdf4-js/compare/master...fridgerator:master

I realize the absolute paths to netcdf arent correct, I wasn't sure how to link correctly with node gyp.

However the changes to the cpp code compile on windows.  Just changing the array instantiations some of the for loops to use legacy c++ style.

**Comment by fridgerator** [comment]
I pushed an update, using `std::vector` works on both platforms and is memory safe.

The last piece to figure out is the absolute path to the netcdf folder in the binding.gyp for windows.  The only thing I can think of is to ensure the user has some environment variable set before building.

**Comment by swillner** [comment]
Finnaly fixed in v0.4.1
